"use client";

import { useState, useTransition } from "react";
import { ChevronUp, Globe, Pencil, Plus, Trash2, X } from "lucide-react";
import { monthlyAmount, suggestedSpendCategories, type BillingPeriod, type Expense, type ExpenseInput, type Product, type SpendTrendPoint } from "@/lib/domain";
import type { Spend } from "@/lib/domain/views";
import { Card, CardHeader, Badge, Button, Field, Input, PageHeading, Select } from "@/components/ui";
import { Donut } from "@/components/donut";
import { integrationIcons } from "@/components/icons";
import { currency, cn } from "@/lib/utils";
import { createExpenseAction, deleteExpenseAction, updateExpenseAction } from "@/app/money/actions";

const billingPeriods: BillingPeriod[] = ["monthly", "yearly"];
type Modal = { mode: "closed" } | { mode: "new" } | { mode: "edit"; expense: Expense };

export function MoneyView({ spend, spendTotal, expenses, spendTrend, products }: { spend: Spend["categories"]; spendTotal: number; expenses: Expense[]; spendTrend: SpendTrendPoint[]; products: Product[] }) {
  const [modal, setModal] = useState<Modal>({ mode: "closed" });
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const previous = spendTrend.length > 1 ? spendTrend[spendTrend.length - 2].amount : 0;
  const delta = previous ? ((spendTotal - previous) / previous) * 100 : 0;
  const maxTrend = Math.max(...spendTrend.map((point) => point.amount), 1);
  const perProduct = products.map((product) => ({ product, amount: expenses.filter((expense) => expense.productId === product.id).reduce((total, expense) => total + monthlyAmount(expense), 0) })).filter((item) => item.amount > 0).sort((a, b) => b.amount - a.amount);
  const close = () => { setModal({ mode: "closed" }); setError(null); };
  const submit = (input: ExpenseInput) => {
    setError(null);
    const editing = modal.mode === "edit" ? modal.expense : null;
    startTransition(async () => {
      const result = editing ? await updateExpenseAction(editing.id, input) : await createExpenseAction(input);
      if (!result.ok) return setError(result.error);
      close();
    });
  };
  const remove = (expense: Expense) => {
    if (!confirm(`Delete ${expense.service}? This can't be undone.`)) return;
    startTransition(async () => { const result = await deleteExpenseAction(expense.id); if (!result.ok) setError(result.error); });
  };
  return <div>
    <PageHeading title="Money" subtitle="Track the monthly costs of running and developing your products." right={<Button variant="primary" onClick={() => setModal({ mode: "new" })}><Plus className="h-4 w-4" /> Add expense</Button>} />
    <div className="grid grid-cols-1 gap-5 lg:grid-cols-[380px_minmax(0,1fr)]">
      <Card className="p-5"><CardHeader title="This month" className="px-0 pt-0" /><div className="mt-3 flex items-end gap-3"><div className="text-4xl font-bold tracking-tight text-fg">{currency(spendTotal)}</div>{previous > 0 && <span className={cn("mb-1.5 flex items-center gap-0.5 text-xs font-medium", delta >= 0 ? "text-warning" : "text-success")}><ChevronUp className={cn("h-3.5 w-3.5", delta < 0 && "rotate-180")} />{Math.abs(delta).toFixed(1)}% vs last month</span>}</div>{spend.length ? <div className="mt-5 flex items-center gap-5"><Donut segments={spend} size={140}><div><div className="text-[11px] uppercase tracking-wide text-faint">Total</div><div className="text-lg font-bold text-fg">{currency(spendTotal)}</div></div></Donut><ul className="flex-1 space-y-3">{spend.map((category) => <li key={category.label} className="text-sm"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ background: category.color }} /><span className="flex-1 text-muted">{category.label}</span><span className="font-medium text-fg">{currency(category.amount)}</span></div><div className="mt-1 pl-[18px]"><div className="h-1 w-full overflow-hidden rounded-full bg-line"><div className="h-full rounded-full" style={{ width: `${Math.round((category.amount / spendTotal) * 100)}%`, background: category.color }} /></div></div></li>)}</ul></div> : <p className="mt-5 text-sm text-muted">No expenses recorded yet. Add domains or shared development tools to get started.</p>}</Card>
      <Card className="flex flex-col p-5"><CardHeader title="6-month trend" className="px-0 pt-0" /><div className="mt-6 flex flex-1 items-end justify-between gap-3">{spendTrend.map((point, index) => { const last = index === spendTrend.length - 1; return <div key={point.month} className="flex flex-1 flex-col items-center gap-2"><div className="text-xs font-medium text-muted">{currency(point.amount)}</div><div className="flex h-40 w-full items-end"><div className={cn("w-full rounded-t-lg transition-all", last ? "bg-accent" : "bg-line-strong")} style={{ height: `${Math.round((point.amount / maxTrend) * 100)}%` }} /></div><div className={cn("text-xs", last ? "font-semibold text-fg" : "text-faint")}>{point.month}</div></div>; })}</div></Card>
    </div>
    <div className="mt-5 grid grid-cols-1 gap-5 lg:grid-cols-[minmax(0,1fr)_360px]">
      <Card><CardHeader title="Expenses" action={<span className="text-xs text-muted">{expenses.length} line items</span>} /><table className="w-full text-sm"><thead><tr className="border-b border-line text-left text-xs text-faint"><th className="px-5 py-2.5 font-medium">Service</th><th className="px-5 py-2.5 font-medium">Product</th><th className="px-5 py-2.5 font-medium">Category</th><th className="px-5 py-2.5 text-right font-medium">Cost</th><th className="w-20 px-3 py-2.5" /></tr></thead><tbody>{expenses.map((expense) => { const Icon = expense.integration ? integrationIcons[expense.integration] : Globe; const product = expense.productId ? products.find((item) => item.id === expense.productId) : undefined; return <tr key={expense.id} className="border-b border-line/60 last:border-0"><td className="px-5 py-3"><div className="flex items-center gap-2.5"><span className="grid h-7 w-7 place-items-center rounded-lg bg-surface-2 text-muted"><Icon className="h-3.5 w-3.5" /></span><span className="font-medium text-fg">{expense.service}</span></div></td><td className="px-5 py-3 text-muted">{product?.name ?? "Studio"}</td><td className="px-5 py-3"><Badge tone="neutral">{expense.category}</Badge></td><td className="px-5 py-3 text-right font-medium text-fg">{currency(expense.amount)}<span className="ml-1 text-xs font-normal text-faint">/{expense.billingPeriod === "yearly" ? "yr" : "mo"}</span></td><td className="px-3 py-3"><div className="flex justify-end gap-1"><Button aria-label={`Edit ${expense.service}`} variant="ghost" onClick={() => setModal({ mode: "edit", expense })}><Pencil className="h-3.5 w-3.5" /></Button><Button aria-label={`Delete ${expense.service}`} variant="ghost" onClick={() => remove(expense)} disabled={pending}><Trash2 className="h-3.5 w-3.5 text-danger" /></Button></div></td></tr>; })}</tbody><tfoot><tr><td colSpan={3} className="px-5 py-3 text-sm font-medium text-muted">Monthly equivalent</td><td className="px-5 py-3 text-right text-base font-bold text-fg">{currency(spendTotal)}</td><td /></tr></tfoot></table></Card>
      <Card><CardHeader title="Spend by product" />{perProduct.length ? <ul className="space-y-3 p-5 pt-3">{perProduct.map(({ product, amount }) => <li key={product.id}><div className="flex items-center gap-2.5 text-sm"><span className="grid h-7 w-7 place-items-center rounded-lg bg-surface-2 text-muted"><Globe className="h-3.5 w-3.5" /></span><span className="flex-1 font-medium text-fg">{product.name}</span><span className="font-medium text-fg">{currency(amount)}</span></div><div className="mt-1.5 pl-[38px]"><div className="h-1.5 w-full overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-accent" style={{ width: `${Math.round((amount / spendTotal) * 100)}%` }} /></div></div></li>)}</ul> : <p className="p-5 pt-3 text-sm text-muted">Assign an expense to a product to see it here.</p>}</Card>
    </div>
    <ExpenseForm key={modal.mode === "edit" ? modal.expense.id : modal.mode} open={modal.mode !== "closed"} initial={modal.mode === "edit" ? modal.expense : undefined} products={products} pending={pending} error={error} onSubmit={submit} onClose={close} />
  </div>;
}

function ExpenseForm({ open, initial, products, pending, error, onSubmit, onClose }: { open: boolean; initial?: Expense; products: Product[]; pending: boolean; error: string | null; onSubmit: (input: ExpenseInput) => void; onClose: () => void }) {
  const [service, setService] = useState(initial?.service ?? ""); const [category, setCategory] = useState(initial?.category ?? ""); const [amount, setAmount] = useState(initial ? String(initial.amount) : ""); const [billingPeriod, setBillingPeriod] = useState<BillingPeriod>(initial?.billingPeriod ?? "monthly"); const [productId, setProductId] = useState(initial?.productId ?? "");
  if (!open) return null;
  return <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/60 p-4 backdrop-blur-sm sm:p-8" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><Card className="my-4 w-full max-w-lg p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold text-fg">{initial ? "Edit expense" : "Add expense"}</h2><Button aria-label="Close" variant="ghost" onClick={onClose}><X className="h-4 w-4" /></Button></div><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onSubmit({ service, category, amount: Number(amount), billingPeriod, productId: productId || undefined }); }}><Field label="Service"><Input autoFocus value={service} onChange={(event) => setService(event.target.value)} placeholder="e.g. Resend, ChatGPT, Namecheap" /></Field><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Field label="Category"><Input required list="expense-category-suggestions" value={category} onChange={(event) => setCategory(event.target.value)} placeholder="e.g. Email" /><datalist id="expense-category-suggestions">{suggestedSpendCategories.map((item) => <option key={item} value={item} />)}</datalist></Field><Field label="Amount (USD)"><Input type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.00" /></Field><Field label="Billed"><Select value={billingPeriod} onChange={(event) => setBillingPeriod(event.target.value as BillingPeriod)}>{billingPeriods.map((period) => <option key={period} value={period}>{period === "monthly" ? "Monthly" : "Yearly"}</option>)}</Select></Field></div><Field label="Product (optional)"><Select value={productId} onChange={(event) => setProductId(event.target.value)}><option value="">Studio-wide / shared</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</Select></Field><p className="text-xs leading-5 text-muted">Choose a suggestion or enter any category. Yearly expenses are included in your monthly total as one-twelfth of their billed amount.</p>{error && <p className="text-sm text-danger">{error}</p>}<div className="flex justify-end gap-2 border-t border-line pt-4"><Button type="button" variant="subtle" onClick={onClose}>Cancel</Button><Button type="submit" variant="primary" disabled={pending}>{pending ? "Saving…" : initial ? "Save changes" : "Add expense"}</Button></div></form></Card></div>;
}
